name       : plasma-thunderbolt
version    : 5.27.4
release    : 46
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.4/plasma-thunderbolt-5.27.4.tar.xz : 28f605034102572d406978b81f891ff5a15d50979116dd3bebc849e5712af4ff
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-2.0-or-later
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Plasma integration for controlling Thunderbolt devices
description: |
    Plasma integration for controlling Thunderbolt devices
optimize   : lto
libsplit   : no
builddeps  :
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - knotifications-devel
rundeps    :
    - bolt
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
