name       : plasma-thunderbolt
version    : 5.27.7
release    : 49
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.7/plasma-thunderbolt-5.27.7.tar.xz : d60ac7888f5b11e53573c41617588bbc5120bc23ac4377265c20a6ebd42df069
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-2.0-or-later
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Plasma integration for controlling Thunderbolt devices
description: |
    Plasma integration for controlling Thunderbolt devices
optimize   : lto
libsplit   : no
builddeps  :
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - knotifications-devel
rundeps    :
    - bolt
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
