name       : plasma-thunderbolt
version    : 5.27.5
release    : 47
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.5/plasma-thunderbolt-5.27.5.tar.xz : 310564c501c6621c3d0f1421865d18839191bc82915ffba555a80214e0db90d5
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-2.0-or-later
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Plasma integration for controlling Thunderbolt devices
description: |
    Plasma integration for controlling Thunderbolt devices
optimize   : lto
libsplit   : no
builddeps  :
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - knotifications-devel
rundeps    :
    - bolt
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
