name       : plasma-thunderbolt
version    : 5.22.1
release    : 27
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.1/plasma-thunderbolt-5.22.1.tar.xz : f8650b5b814eeb19aaf30da939418010cb7591718b139027480aa9abbb9a11c6
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-2.0-or-later
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Plasma integration for controlling Thunderbolt devices
description: |
    Plasma integration for controlling Thunderbolt devices
optimize   : lto
libsplit   : no
builddeps  :
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - knotifications-devel
rundeps    :
    - bolt
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
