name       : plasma-thunderbolt
version    : 5.17.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.0/plasma-thunderbolt-5.17.0.tar.xz : 8e244a2f6e872451166deaf454a057110761acec054655986d55576af38a23e1
license    :
    - GFDL-2.0-or-later
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Plasma integration for controlling Thunderbolt devices
description: |
    Plasma integration for controlling Thunderbolt devices
builddeps  :
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kdeclarative-devel
    - kcmutils-devel
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
rundeps    :
    - bolt
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
