name       : plasma-thunderbolt
version    : 5.17.5
release    : 5
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.5/plasma-thunderbolt-5.17.5.tar.xz : 3743f9841d269d51f1b1419e24d5cd1b26a0ba5a90e76b531328a8cc43184382
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-2.0-or-later
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Plasma integration for controlling Thunderbolt devices
description: |
    Plasma integration for controlling Thunderbolt devices
builddeps  :
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kdbusaddons-devel
    - kdeclarative-devel
    - kcmutils-devel
    - kcoreaddons-devel
    - ki18n-devel
    - knotifications-devel
rundeps    :
    - bolt
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
